# Generated by Django 5.0.1 on 2024-01-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogs', '0003_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_category',
            name='blogcat_description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='u_message',
            field=models.TextField(max_length=200),
        ),
    ]
