# Generated by Django 5.0.1 on 2024-01-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogs', '0004_alter_blog_category_blogcat_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_email', models.EmailField(max_length=254)),
                ('s_name', models.TextField(max_length=500)),
                ('s_package', models.TextField(max_length=500)),
            ],
        ),
    ]
