# Generated by Django 5.0.1 on 2024-01-19 09:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogs', '0005_subscription_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=60)),
                ('blog_cover', models.ImageField(upload_to='images/')),
                ('blog_description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
