# Generated by Django 5.0.1 on 2024-01-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogs', '0006_blog_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog_post',
        ),
    ]
