# Generated by Django 5.0.1 on 2024-02-02 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogs', '0010_blog_post_like_count_blog_post_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_mail', models.EmailField(max_length=100)),
                ('comment', models.TextField(max_length=400)),
                ('Blog_name', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myBlogs.blog_post')),
            ],
        ),
    ]
